// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
)

type Movie struct {
	ID        int64
	CreatedAt sql.NullTime
	Title     string
	Year      int32
	Runtime   int32
	Genres    []string
}
