// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
)

type Movie struct {
	ID        int64        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	Title     string       `json:"title"`
	Year      int32        `json:"year"`
	Runtime   Runtime      `json:"runtime"`
	Genres    []string     `json:"genres"`
}
